# Test configuration for Foundation Storage Engine
# Provides minimal defaults suitable for integration testing.
storage:
  provider: filesystem
  filesystem:
    base_dir: "./testdata"

auth:
  type: awsv4
  identity: test-identity
  credential: test-credential

server:
  listen: ":8080"

logging:
  level: debug
  format: text
