{{- if .Values.configFile.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundation-storage-engine.fullname" . }}-config
  labels:
    {{- include "foundation-storage-engine.labels" . | nindent 4 }}
data:
  {{ .Values.configFile.filename }}: |-
{{ .Values.configFile.content | indent 4 }}
{{- end }}
