name: Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better detection

      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || (github.event.before != '0000000000000000000000000000000000000000' && github.event.before || github.sha) }}
          head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          extra_args: --only-verified --fail-on-finding


  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets
        run: |
          detect-secrets scan --all-files --force-use-all-plugins > .secrets.new

      - name: Compare with baseline
        run: |
          if [ -f .secrets.baseline ]; then
            # Use non-interactive mode with JSON output
            detect-secrets audit --report .secrets.baseline .secrets.new || echo "No new secrets detected"
          else
            mv .secrets.new .secrets.baseline
            echo "Created initial secrets baseline"
          fi

